DROP TABLE Socyal.USER;
DROP TABLE Socyal.CHECKIN;
DROP TABLE Socyal.TIMING;
DROP TABLE Socyal.MERCHANT;
DROP TABLE Socyal.CONTACT;
DROP TABLE Socyal.ADDRESS;
DROP TABLE Socyal.LOCALITY;
DROP SCHEMA Socyal;