DROP TRIGGER Socyal.CHECKIN_AUDIT_INSERT_TRIGGER;
DROP TRIGGER Socyal.CHECKIN_AUDIT_UPDATE_TRIGGER;

DROP TRIGGER Socyal.USER_AUDIT_INSERT_TRIGGER;
DROP TRIGGER SOcyal.USER_AUDIT_UPDATE_TRIGGER;

DROP TABLE Socyal.USER;
DROP TABLE Socyal.CHECKIN;
DROP TABLE Socyal.TIMING;
DROP TABLE Socyal.MERCHANT;
DROP TABLE Socyal.CONTACT;
DROP TABLE Socyal.ADDRESS;
DROP TABLE Socyal.LOCALITY;

DROP SCHEMA Socyal;