-- add column DISH.VEGNONVEG
ALTER TABLE bna.`DISH`
ADD COLUMN `VEGNONVEG` INT NOT NULL DEFAULT 0 AFTER `NAME_ID`

-- add column MERCHANT.CAN_EDIT
ALTER TABLE bna.`MERCHANT`
ADD COLUMN `CAN_EDIT` BIT NULL DEFAULT 0 AFTER `IS_ACTIVE`