CREATE SCHEMA IF NOT EXISTS `bna` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `bna`.`LOCALITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NULL,
  `CITY` VARCHAR(100) NULL,
  `LATITUDE` DOUBLE NULL,
  `LONGITUDE` DOUBLE NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS` VARCHAR(1000) NULL,
  `LOCALITY_ID` INT NOT NULL,
  `CITY` VARCHAR(100) NULL,
  `STATE` VARCHAR(100) NULL,
  `COUNTRY` VARCHAR(100) NULL,
  `ZIP` VARCHAR(20) NULL,
  `LATITUDE` DOUBLE NULL,
  `LONGITUDE` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ADDRESS_LOCALITY_FK`
    FOREIGN KEY (`LOCALITY_ID`)
    REFERENCES `bna`.`LOCALITY` (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

  
CREATE TABLE `bna`.`CONTACT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PHONE1` VARCHAR(20) NOT NULL,
  `PHONE2` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;
  
CREATE TABLE `bna`.`MERCHANT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME_ID` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `ADDRESS_ID` INT NOT NULL,
  `CONTACT_ID` INT NOT NULL,
  `IMAGE_URL` VARCHAR(255) NOT NULL,
  `RATING` DOUBLE NULL,
  `AVERAGE_COST` DOUBLE NOT NULL,
  `CHECKINS` INT DEFAULT 0,
  `CUISINE` VARCHAR(255) NOT NULL,
  `TYPE`  VARCHAR(255) NOT NULL,
  `PROMOTION` INT DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `MERCHANT_ADDRESS_FK_idx` (`ADDRESS_ID` ASC),
  INDEX `MERCHANT_CONTACT_FK_idx` (`CONTACT_ID` ASC),
  CONSTRAINT `MERCHANT_ADDRESS_FK`
    FOREIGN KEY (`ADDRESS_ID`)
    REFERENCES `bna`.`ADDRESS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MERCHANT_CONTACT_FK`
    FOREIGN KEY (`CONTACT_ID`)
    REFERENCES `bna`.`CONTACT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`TIMING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` INT NOT NULL,
  `DAY` VARCHAR(10) NOT NULL,
  `OPEN` VARCHAR(4) NOT NULL,
  `CLOSE` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MERCHANT_FK`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `bna`.`MERCHANT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`SUGGESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`CUISINE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`DISH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NULL,
  `NAME_ID` VARCHAR(100) NOT NULL,
  `SUGGESTION_ID` INT NULL,
  `CUISINE_ID` INT NULL,
  `MERCHANT_ID` INT NOT NULL,
  `IMAGE_URL` VARCHAR(250) NULL,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  `INITIAL_DUMP` INT DEFAULT 0,
  PRIMARY KEY (`ID`),
  CONSTRAINT `DISH_MERCHANT_FK`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `bna`.`MERCHANT` (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`RECOMMENDATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DISH_ID` INT NULL,
  `USER_ID` INT NOT NULL,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  `DESCRIPTION` VARCHAR(500) NULL,
  `CREATED_DATETIME` TIMESTAMP NULL,
  `UPDATED_DATETIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UID` VARCHAR(100) NOT NULL,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NULL,
  `IMAGE_URL` VARCHAR(500) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `CREATED_DATETIME` TIMESTAMP NULL,
  `UPDATED_DATETIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE `bna`.`ITEM_IMAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `URL` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;