-- create new table - CITY
CREATE TABLE `bna`.`CITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(25) NULL,
  `NAME_ID` VARCHAR(25) NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

INSERT INTO `bna`.`CITY` (`NAME`, `NAME_ID`) VALUES ('Hyderabad', 'hyderabad');

-- alter LOCALITY with city changes
ALTER TABLE bna.`LOCALITY`
DROP COLUMN `CITY`,
DROP COLUMN `CREATED_DATETIME`,
DROP COLUMN `UPDATED_DATETIME`,
ADD COLUMN `NAME_ID` VARCHAR(50) NOT NULL AFTER `NAME`,
ADD COLUMN `CITY_ID` INT(11) NOT NULL AFTER `NAME_ID`;

UPDATE `bna`.`LOCALITY` SET `CITY_ID`=1;

-- add constraint LOCALITY_CITY_FK
ALTER TABLE bna.`LOCALITY`
ADD CONSTRAINT `LOCALITY_CITY_FK`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `bna`.`CITY` (`ID`);
    
-- add column RECOMMENDATION.RATING
ALTER TABLE bna.`RECOMMENDATION`
ADD COLUMN `RATING` DECIMAL(2, 1) NOT NULL AFTER `USER_ID`;

-- add column DISH.RATING
ALTER TABLE bna.`DISH`
ADD COLUMN `RATING` DECIMAL(2, 1) NULL AFTER `NAME_ID`;
