-- add column LOCALITY.IS_ACTIVE
ALTER TABLE bna.`LOCALITY`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `CITY_ID`;

-- add column CUISINE.IS_ACTIVE
ALTER TABLE bna.`CUISINE`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `NAME_ID`;

-- add column SUGGESTION.IS_ACTIVE
ALTER TABLE bna.`SUGGESTION`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `NAME_ID`;