-- create new table - CITY
CREATE TABLE `bna`.`CITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(25) NULL,
  `NAME_ID` VARCHAR(25) NULL,
  PRIMARY KEY (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

INSERT INTO `bna`.`CITY` (`NAME`, `NAME_ID`) VALUES ('Hyderabad', 'hyderabad');

-- alter LOCALITY with city changes
ALTER TABLE bna.`LOCALITY`
DROP COLUMN `CITY`,
DROP COLUMN `CREATED_DATETIME`,
DROP COLUMN `UPDATED_DATETIME`,
ADD COLUMN `NAME_ID` VARCHAR(50) NOT NULL AFTER `NAME`,
ADD COLUMN `CITY_ID` INT(11) NOT NULL AFTER `NAME_ID`;

UPDATE `bna`.`LOCALITY` SET `CITY_ID`=1;

-- add constraint LOCALITY_CITY_FK
ALTER TABLE bna.`LOCALITY`
ADD CONSTRAINT `LOCALITY_CITY_FK`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `bna`.`CITY` (`ID`);
    
-- add column RECOMMENDATION.RATING
ALTER TABLE bna.`RECOMMENDATION`
ADD COLUMN `RATING` DECIMAL(2, 1) NOT NULL AFTER `USER_ID`;

-- add column DISH.RATING
ALTER TABLE bna.`DISH`
ADD COLUMN `RATING` DECIMAL(2, 1) NULL AFTER `NAME_ID`;

-- add column USER.CREDIBILITY
ALTER TABLE bna.`USER`
ADD COLUMN `CREDIBILITY` DECIMAL(2, 1) NOT NULL DEFAULT 2.5 AFTER `NAME_ID`;

-- create new table - MERCHANT_CUISINE_RATING
CREATE TABLE `bna`.`MERCHANT_CUISINE_RATING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` INT NOT NULL,
  `CUISINE_ID` INT NOT NULL,
  `RATING` DECIMAL(2, 1),
  `DISH_COUNT` INT,
  `CREATED_DATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MCR_MERCHANT_FK`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `bna`.`MERCHANT` (`ID`),
  CONSTRAINT `MCR_CUISINE_FK`
    FOREIGN KEY (`CUISINE_ID`)
    REFERENCES `bna`.`CUISINE` (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

-- create new table - MERCHANT_SUGGESTION_RATING
CREATE TABLE `bna`.`MERCHANT_SUGGESTION_RATING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` INT NOT NULL,
  `SUGGESTION_ID` INT NOT NULL,
  `RATING` DECIMAL(2, 1),
  `DISH_COUNT` INT,
  `CREATED_DATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MSR_MERCHANT_FK`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `bna`.`MERCHANT` (`ID`),
  CONSTRAINT `MSR_SUGGESTION_FK`
    FOREIGN KEY (`SUGGESTION_ID`)
    REFERENCES `bna`.`SUGGESTION` (`ID`)) 
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

-- add column CUISINE.IMAGE_URL, CUISINE.THUMBNAIL
ALTER TABLE bna.`CUISINE`
ADD COLUMN `IMAGE_URL` VARCHAR(100) AFTER `NAME_ID`,
ADD COLUMN `THUMBNAIL` VARCHAR(100) AFTER `NAME_ID`;

-- add column SUGGESTION.IMAGE_URL, CUISINE.THUMBNAIL
ALTER TABLE bna.`SUGGESTION`
ADD COLUMN `IMAGE_URL` VARCHAR(100) AFTER `NAME_ID`,
ADD COLUMN `THUMBNAIL` VARCHAR(100) AFTER `NAME_ID`;

-- alter RECOMMENDATION drop IS_ACTIVE
ALTER TABLE bna.`RECOMMENDATION`
DROP COLUMN `IS_ACTIVE`