-- add column LOCALITY.IS_ACTIVE
ALTER TABLE bna.`LOCALITY`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `CITY_ID`;

-- add column CUISINE.IS_ACTIVE
ALTER TABLE bna.`CUISINE`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `NAME_ID`;

-- add column SUGGESTION.IS_ACTIVE
ALTER TABLE bna.`SUGGESTION`
ADD COLUMN `IS_ACTIVE` BIT NOT NULL DEFAULT 1 AFTER `NAME_ID`;

-- alter column bna.VEGNONVEG make nullable
ALTER TABLE bna.`DISH` MODIFY `VEGNONVEG` INT

-- set null values in place of 0 in bna.VEGNONVEG
UPDATE bna.`DISH` SET `VEGNONVEG` = NULL WHERE `VEGNONVEG` = 0

-- add column CUISINE.VEGNONVEG_ID
ALTER TABLE bna.`CUISINE`
ADD COLUMN `VEGNONVEG_ID` INT NOT NULL DEFAULT 3 AFTER `IS_ACTIVE`,
ADD CONSTRAINT `CUISINE_VEGNONVEG_FK` FOREIGN KEY (`VEGNONVEG_ID`) 
REFERENCES `bna`.`VEGNONVEG` (`ID`);

-- add column SUGGESTION.VEGNONVEG_ID
ALTER TABLE bna.`SUGGESTION`
ADD COLUMN `VEGNONVEG_ID` INT NOT NULL DEFAULT 3 AFTER `IS_ACTIVE`,
ADD CONSTRAINT `SUGGESTION_VEGNONVEG_FK` FOREIGN KEY (`VEGNONVEG_ID`) 
REFERENCES `bna`.`VEGNONVEG` (`ID`);

-- alter table bna.RECOMMENDATION charset to utf8mb4
ALTER TABLE bna.`RECOMMENDATION` CONVERT TO CHARACTER SET utf8mb4

-- alter column bna.RECOMMENDATION.DESCRIPTION
ALTER TABLE bna.`RECOMMENDATION` 
MODIFY `DESCRIPTION` VARCHAR(300) COLLATE utf8mb4_bin DEFAULT NULL

-- add column DISH.COST
ALTER TABLE bna.`DISH`
ADD COLUMN `COST` VARCHAR(7) AFTER `NAME_ID`;